#!/bin/bash

# Install Java
yum -y install java-1.8.0-openjdk

# Import GPG Key
rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

# Install Repo
cat > /etc/yum.repos.d/elasticsearch5.repo << 'EOF'
[elasticsearch-5.x]
name=Elasticsearch repository for 5.x packages
baseurl=https://artifacts.elastic.co/packages/5.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md
EOF

# Install Elasticsearch
yum -y install elasticsearch

# Install Plugins
/usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-phonetic
/usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu

# Services
systemctl start elasticsearch
systemctl enable elasticsearch
